name: CI Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle Build Cache
        uses: gradle/actions/setup-gradle@v5

      - name: Install Android NDK & CMake
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.14206865" "cmake;4.1.2"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Run Rust Tests
        working-directory: ./rust
        run: cargo test

      - name: Build and Test Kotlin
        run: |
          chmod +x gradlew
          ./gradlew build test --stacktrace
