name: CI Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Load Build Environment
        run: cat build.env >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle Build Cache
        uses: gradle/actions/setup-gradle@v6

      - name: Install Android NDK & CMake
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}" "cmake;${{ env.CMAKE_VERSION }}"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.RUST_TARGET }}
          components: llvm-tools-preview

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          cache-all-crates: true

      - name: Install Rust Tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk,cargo-llvm-cov

      - name: Run Rust Tests & Coverage
        working-directory: ./rust
        # <-- Replaces `cargo test` to run tests AND generate the lcov file
        run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Build and Test Kotlin & Coverage
        run: |
          chmod +x gradlew
          ./gradlew build test koverXmlReport --stacktrace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./rust/lcov.info,./app/build/reports/kover/report.xml
          fail_ci_if_error: true